# Generated by Django 5.2.16 on 2026-07-29 07:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('offline', 'Offline'), ('connecting', 'Connecting'), ('online', 'Online'), ('busy', 'Busy'), ('error', 'Error'), ('disabled', 'Disabled')], default='offline', max_length=32)),
                ('version', models.CharField(blank=True, max_length=64)),
                ('operating_system', models.CharField(blank=True, max_length=128)),
                ('last_connected_at', models.DateTimeField(blank=True, null=True)),
                ('last_activity_at', models.DateTimeField(blank=True, null=True)),
                ('capabilities', models.JSONField(blank=True, default=list)),
                ('development_token_hash', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
