# Generated by Django 5.2.16 on 2026-07-29 19:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commands', '0002_command_conversation_command_requested_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_id', models.UUIDField(unique=True)),
                ('tool_name', models.CharField(max_length=255)),
                ('tool_input', models.JSONField(blank=True, default=dict)),
                ('tool_use_id', models.CharField(blank=True, max_length=255)),
                ('decision', models.CharField(choices=[('pending', 'Pending'), ('allowed', 'Allowed'), ('denied', 'Denied'), ('expired', 'Expired')], default='pending', max_length=16)),
                ('decision_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('command', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_requests', to='commands.command')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permission_decisions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
